# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_Title', models.CharField(max_length=1024)),
                ('Aritcle_Text', models.CharField(max_length=102400)),
                ('Aritcle_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=1024)),
                ('User_Passwd', models.CharField(max_length=1024)),
                ('User_Aritcle', models.ManyToManyField(to='index.Article')),
            ],
        ),
    ]
